podTemplate(containers: [
containerTemplate(
name: 'gradle',
image: 'gradle',
command: 'sleep',
args: '30d'
),
]) {
node(POD_LABEL) {
  stage('Run pipeline against a gradle project - test MAIN') {
  container('gradle') {
    stage('Build a gradle project') {
      echo "I am the ${env.BRANCH_NAME} branch"
// from the git plugin
// https://www.jenkins.io/doc/pipeline/steps/git/
        git 'https://github.com/leopoldstotch1234/week5.git'
        sh '''
        cd Chapter08/sample1
	chmod +x gradlew
        '''
        }
    }
    stage('Code coverage') {
      sh 'printenv'
      echo "My CC branch is: ${env.BRANCH_NAME}"
      if (env.BRANCH_NAME != "master") {
      echo "I am the ${env.BRANCH_NAME} branch"
      }
    }
    stage("Tests") {
	    if (env.BRANCH_NAME == "master") {
      echo "I am the ${env.BRANCH_NAME} branch"
		    try {
                        sh '''
			echo "running check"
        	            pwd
               		    cd Chapter08/sample1
                          ./gradlew test
                          ./gradlew jacocoTestReport
                        '''
                    } catch (Exception E) {
                        echo 'Failure detected'
                    }
      }
		      
          }
          
}
}
}


